Criação Arrays NumPy

In [1]:
import numpy as np

In [2]:
arr1 = np.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [4]:
print(arr1)
print(type(arr1))
print(arr1.shape)

[10 21 32 43 48 15 76 57 89]
<class 'numpy.ndarray'>
(9,)


Indexação em Arrays NumPy

In [5]:
arr1[4]

np.int64(48)

In [6]:
arr1[1:4]

array([21, 32, 43])

In [7]:
arr1[1:4+1]

array([21, 32, 43, 48])

In [8]:
indices = [1, 2, 5, 6]

In [9]:
arr1[indices]

array([21, 32, 15, 76])

In [14]:
# Cria uma máscara booleana para os elementos pares
mask = (arr1 % 2 == 0)

In [16]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [15]:
arr1[mask]

array([10, 32, 48, 76])

In [17]:
arr1[0] = 100
arr1

array([100,  21,  32,  43,  48,  15,  76,  57,  89])

In [18]:
try: 
    arr1[0] = 'Novo elemento'
except:
    print('Operação não permitida!')

Operação não permitida!
