In [1]:
import numpy as np

In [2]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
array.shape

(2, 3)

In [4]:
array2 = np.ones((2,3))
array2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
lista = [[13, 81, 21], [0, 34, 59], [21, 48, 94]]
lista

[[13, 81, 21], [0, 34, 59], [21, 48, 94]]

In [7]:
array3 = np.matrix(lista)
array3

matrix([[13, 81, 21],
        [ 0, 34, 59],
        [21, 48, 94]])

In [ ]:
array3.shape

(3, 3)

In [13]:
array3.size

9

In [14]:
array3[2, 1]

np.int64(48)

In [15]:
array3[0:2, 2]

matrix([[21],
        [59]])

In [16]:
array3[1, ]

matrix([[ 0, 34, 59]])

In [18]:
array3[1, 0] = 100
array3

matrix([[ 13,  81,  21],
        [100,  34,  59],
        [ 21,  48,  94]])

In [19]:
x = np.array([1, 2]) # Numpy decide o tipo de dados
y = np.array([1.0, 2.0])
z = np.array([1, 2], dtype =np.float64) # Foi forçado um tipo de dado em particular

In [20]:
print(x.dtype, y.dtype, z.dtype)

int64 float64 float64


In [21]:
array4 = np.array([[24, 76, 92, 14], [47, 35, 89, 2]], dtype = np.float64)
array4

array([[24., 76., 92., 14.],
       [47., 35., 89.,  2.]])

In [ ]:
array4.itemsize # tamanho em bytes de cada elemento do array

8

In [ ]:
array4.nbytes # tamanho total em bytes do array 

64

In [ ]:
array4.ndim # numero de dimensoes

2