In [1]:
import numpy as np

In [2]:
array = np.arange(1, 10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sum(array)

np.int64(45)

In [ ]:
np.prod(array) #type: ignore

np.int64(362880)

In [5]:
np.cumsum(array)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [6]:
array2 = np.array([3, 2, 1])
array3 = np.array([1, 2, 3])

In [7]:
array4 = np.add(array2, array3)

In [8]:
array4

array([4, 4, 4])

In [9]:
array5 = np.array([[1, 2], [3, 4]])
array6 = np.array([[5, 6], [0, 7]])

In [10]:
array5.shape

(2, 2)

In [11]:
array6.shape

(2, 2)

In [13]:
array5

array([[1, 2],
       [3, 4]])

In [14]:
array6

array([[5, 6],
       [0, 7]])

In [ ]:
# Multiplicar as duas matrizes
array7 = np.dot(array5, array6)
# array7 = array5 @ array6
# array7 = np.tensordot(array5, array6, axes = ((1), (0)))
array7

array([[ 5, 20],
       [15, 46]])