In [1]:
import numpy as np

In [2]:
array = np.diag(np.arange(3))
array

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [ ]:
array[:, 2]

array([0, 1, 0])

In [7]:
array2 = np.arange(10)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# [start:end:step]
array2[2:9:3]

array([2, 5, 8])

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [12]:
a == b

array([False,  True, False,  True])

In [14]:
np.array_equal(array, array2)

False

In [15]:
array2.min()

np.int64(0)

In [16]:
array2.max()

np.int64(9)

In [17]:
np.array([1, 2, 3]) + 1.5

array([2.5, 3.5, 4.5])

In [18]:
array3 = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

In [19]:
np.around(array3)

array([1., 2., 2., 2., 4., 4.])

In [22]:
array4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
array4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

O método flatten() com NumPy é usado para criar uma cópia unidimensional (ou "achatada") de um array multidimensional. Isso significa que o método cria um novo array unidimensional, que contém todos os elementos do array multidimensional original, mas que está organizado em uma única linha. A ordem dos elementos no novo array unidimensional segue a ordem dos elementos no array multidimensional original.

In [21]:
array5 = array4.flatten()
array5

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
array6 = np.array([1, 2, 3])
array6

array([1, 2, 3])

In [24]:
np.repeat(array6, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [26]:
np.tile(array6, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [30]:
array7 = np.array([5, 6])
array7

array([5, 6])

In [28]:
array8 = np.copy(array7)

In [29]:
array8

array([5, 6])